import { Card } from "./card";

export const CONFUSING: Card[] = [
  // 지계(ji계)
  { char: "じ", romaji: "ji", kor: "지", group: "ji계" },
  { char: "ぢ", romaji: "ji", kor: "지", group: "ji계" },
  { char: "ジ", romaji: "ji", kor: "지", group: "ji계" },
  { char: "ヂ", romaji: "ji", kor: "지", group: "ji계" },

  // 즈계(zu계)
  { char: "ず", romaji: "zu", kor: "즈", group: "zu계" },
  { char: "づ", romaji: "zu", kor: "즈", group: "zu계" },
  { char: "ズ", romaji: "zu", kor: "즈", group: "zu계" },
  { char: "ヅ", romaji: "zu", kor: "즈", group: "zu계" },

  // 바/파계(ba/pa계)
  { char: "ば", romaji: "ba", kor: "바", group: "ba/pa계" },
  { char: "ぱ", romaji: "pa", kor: "파", group: "ba/pa계" },
  { char: "バ", romaji: "ba", kor: "바", group: "ba/pa계" },
  { char: "パ", romaji: "pa", kor: "파", group: "ba/pa계" },

  // 비/피계(bi/pi계)
  { char: "び", romaji: "bi", kor: "비", group: "bi/pi계" },
  { char: "ぴ", romaji: "pi", kor: "피", group: "bi/pi계" },
  { char: "ビ", romaji: "bi", kor: "비", group: "bi/pi계" },
  { char: "ピ", romaji: "pi", kor: "피", group: "bi/pi계" },

  // 부/푸계(bu/pu계)
  { char: "ぶ", romaji: "bu", kor: "부", group: "bu/pu계" },
  { char: "ぷ", romaji: "pu", kor: "푸", group: "bu/pu계" },
  { char: "ブ", romaji: "bu", kor: "부", group: "bu/pu계" },
  { char: "プ", romaji: "pu", kor: "푸", group: "bu/pu계" },

  // 베/페계(be/pe계)
  { char: "べ", romaji: "be", kor: "베", group: "be/pe계" },
  { char: "ぺ", romaji: "pe", kor: "페", group: "be/pe계" },
  { char: "ベ", romaji: "be", kor: "베", group: "be/pe계" },
  { char: "ペ", romaji: "pe", kor: "페", group: "be/pe계" },

  // 보/포계(bo/po계)
  { char: "ぼ", romaji: "bo", kor: "보", group: "bo/po계" },
  { char: "ぽ", romaji: "po", kor: "포", group: "bo/po계" },
  { char: "ボ", romaji: "bo", kor: "보", group: "bo/po계" },
  { char: "ポ", romaji: "po", kor: "포", group: "bo/po계" },

  // 가기구게고계(ga/gi/gu/ge/go계)
  { char: "が", romaji: "ga", kor: "가", group: "ga계" },
  { char: "ぎ", romaji: "gi", kor: "기", group: "ga계" },
  { char: "ぐ", romaji: "gu", kor: "구", group: "ga계" },
  { char: "げ", romaji: "ge", kor: "게", group: "ga계" },
  { char: "ご", romaji: "go", kor: "고", group: "ga계" },
  { char: "ガ", romaji: "ga", kor: "가", group: "ga계" },
  { char: "ギ", romaji: "gi", kor: "기", group: "ga계" },
  { char: "グ", romaji: "gu", kor: "구", group: "ga계" },
  { char: "ゲ", romaji: "ge", kor: "게", group: "ga계" },
  { char: "ゴ", romaji: "go", kor: "고", group: "ga계" },

  // 자지즈제조계(za/ji/zu/ze/zo계)
  { char: "ざ", romaji: "za", kor: "자", group: "za계" },
  { char: "じ", romaji: "ji", kor: "지", group: "za계" },
  { char: "ず", romaji: "zu", kor: "즈", group: "za계" },
  { char: "ぜ", romaji: "ze", kor: "제", group: "za계" },
  { char: "ぞ", romaji: "zo", kor: "조", group: "za계" },
  { char: "ザ", romaji: "za", kor: "자", group: "za계" },
  { char: "ジ", romaji: "ji", kor: "지", group: "za계" },
  { char: "ズ", romaji: "zu", kor: "즈", group: "za계" },
  { char: "ゼ", romaji: "ze", kor: "제", group: "za계" },
  { char: "ゾ", romaji: "zo", kor: "조", group: "za계" },

  // 다디두데도계(da/ji/zu/de/do계)
  { char: "だ", romaji: "da", kor: "다", group: "da계" },
  { char: "ぢ", romaji: "ji", kor: "지", group: "da계" },
  { char: "づ", romaji: "zu", kor: "즈", group: "da계" },
  { char: "で", romaji: "de", kor: "데", group: "da계" },
  { char: "ど", romaji: "do", kor: "도", group: "da계" },
  { char: "ダ", romaji: "da", kor: "다", group: "da계" },
  { char: "ヂ", romaji: "ji", kor: "지", group: "da계" },
  { char: "ヅ", romaji: "zu", kor: "즈", group: "da계" },
  { char: "デ", romaji: "de", kor: "데", group: "da계" },
  { char: "ド", romaji: "do", kor: "도", group: "da계" },

  // 히라가나 요음
  { char: "きゃ", romaji: "kya", kor: "캬", group: "youon" },
  { char: "きゅ", romaji: "kyu", kor: "큐", group: "youon" },
  { char: "きょ", romaji: "kyo", kor: "쿄", group: "youon" },
  { char: "しゃ", romaji: "sha", kor: "샤", group: "youon" },
  { char: "しゅ", romaji: "shu", kor: "슈", group: "youon" },
  { char: "しょ", romaji: "sho", kor: "쇼", group: "youon" },
  { char: "ちゃ", romaji: "cha", kor: "챠", group: "youon" },
  { char: "ちゅ", romaji: "chu", kor: "츄", group: "youon" },
  { char: "ちょ", romaji: "cho", kor: "쵸", group: "youon" },
  { char: "にゃ", romaji: "nya", kor: "냐", group: "youon" },
  { char: "にゅ", romaji: "nyu", kor: "뉴", group: "youon" },
  { char: "にょ", romaji: "nyo", kor: "뇨", group: "youon" },
  { char: "ひゃ", romaji: "hya", kor: "햐", group: "youon" },
  { char: "ひゅ", romaji: "hyu", kor: "휴", group: "youon" },
  { char: "ひょ", romaji: "hyo", kor: "효", group: "youon" },
  { char: "みゃ", romaji: "mya", kor: "먀", group: "youon" },
  { char: "みゅ", romaji: "myu", kor: "뮤", group: "youon" },
  { char: "みょ", romaji: "myo", kor: "묘", group: "youon" },
  { char: "りゃ", romaji: "rya", kor: "랴", group: "youon" },
  { char: "りゅ", romaji: "ryu", kor: "류", group: "youon" },
  { char: "りょ", romaji: "ryo", kor: "료", group: "youon" },
  { char: "ぎゃ", romaji: "gya", kor: "갸", group: "youon" },
  { char: "ぎゅ", romaji: "gyu", kor: "규", group: "youon" },
  { char: "ぎょ", romaji: "gyo", kor: "교", group: "youon" },
  { char: "じゃ", romaji: "ja", kor: "쟈", group: "youon" },
  { char: "じゅ", romaji: "ju", kor: "쥬", group: "youon" },
  { char: "じょ", romaji: "jo", kor: "죠", group: "youon" },
  { char: "びゃ", romaji: "bya", kor: "뱌", group: "youon" },
  { char: "びゅ", romaji: "byu", kor: "뷰", group: "youon" },
  { char: "びょ", romaji: "byo", kor: "뵤", group: "youon" },
  { char: "ぴゃ", romaji: "pya", kor: "퍄", group: "youon" },
  { char: "ぴゅ", romaji: "pyu", kor: "퓨", group: "youon" },
  { char: "ぴょ", romaji: "pyo", kor: "표", group: "youon" },

  // 카타카나 요음
  { char: "キャ", romaji: "kya", kor: "캬", group: "youon" },
  { char: "キュ", romaji: "kyu", kor: "큐", group: "youon" },
  { char: "キョ", romaji: "kyo", kor: "쿄", group: "youon" },
  { char: "シャ", romaji: "sha", kor: "샤", group: "youon" },
  { char: "シュ", romaji: "shu", kor: "슈", group: "youon" },
  { char: "ショ", romaji: "sho", kor: "쇼", group: "youon" },
  { char: "チャ", romaji: "cha", kor: "챠", group: "youon" },
  { char: "チュ", romaji: "chu", kor: "츄", group: "youon" },
  { char: "チョ", romaji: "cho", kor: "쵸", group: "youon" },
  { char: "ニャ", romaji: "nya", kor: "냐", group: "youon" },
  { char: "ニュ", romaji: "nyu", kor: "뉴", group: "youon" },
  { char: "ニョ", romaji: "nyo", kor: "뇨", group: "youon" },
  { char: "ヒャ", romaji: "hya", kor: "햐", group: "youon" },
  { char: "ヒュ", romaji: "hyu", kor: "휴", group: "youon" },
  { char: "ヒョ", romaji: "hyo", kor: "효", group: "youon" },
  { char: "ミャ", romaji: "mya", kor: "먀", group: "youon" },
  { char: "ミュ", romaji: "myu", kor: "뮤", group: "youon" },
  { char: "ミョ", romaji: "myo", kor: "묘", group: "youon" },
  { char: "リャ", romaji: "rya", kor: "랴", group: "youon" },
  { char: "リュ", romaji: "ryu", kor: "류", group: "youon" },
  { char: "リョ", romaji: "ryo", kor: "료", group: "youon" },
  { char: "ギャ", romaji: "gya", kor: "갸", group: "youon" },
  { char: "ギュ", romaji: "gyu", kor: "규", group: "youon" },
  { char: "ギョ", romaji: "gyo", kor: "교", group: "youon" },
  { char: "ジャ", romaji: "ja", kor: "쟈", group: "youon" },
  { char: "ジュ", romaji: "ju", kor: "쥬", group: "youon" },
  { char: "ジョ", romaji: "jo", kor: "죠", group: "youon" },
  { char: "ビャ", romaji: "bya", kor: "뱌", group: "youon" },
  { char: "ビュ", romaji: "byu", kor: "뷰", group: "youon" },
  { char: "ビョ", romaji: "byo", kor: "뵤", group: "youon" },
  { char: "ピャ", romaji: "pya", kor: "퍄", group: "youon" },
  { char: "ピュ", romaji: "pyu", kor: "퓨", group: "youon" },
  { char: "ピョ", romaji: "pyo", kor: "표", group: "youon" },
];
